tweaks to install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -16,17 +16,15 @@ fi
 
 # Install yay
 echo -e "${COLOR_INFO}Installing yay...${COLOR_RESET}"
-git clone https://aur.archlinux.org/yay-git.git || { echo "${COLOR_ERROR}Failed to clone yay${COLOR_RESET}"; exit 1; }
-cd yay-git/
-makepkg -si || { echo "${COLOR_ERROR}Failed to install yay${COLOR_RESET}"; exit 1; }
-cd ..
+git clone https://aur.archlinux.org/yay-git.git ~/yay-git || { echo "${COLOR_ERROR}Failed to clone yay${COLOR_RESET}"; exit 1; }
+(cd ~/yay-git && makepkg -si) || { echo "${COLOR_ERROR}Failed to install yay${COLOR_RESET}"; exit 1; }
 
 # Install required packages
 echo -e "${COLOR_INFO}Installing required packages...${COLOR_RESET}"
 yay -S - < ./packages || { echo "${COLOR_ERROR}Failed to install required packages${COLOR_RESET}"; exit 1; }
 
 # Enable Flathub
-echo -e "${COLOR_INFO}Enabling Flathub${COLOR_RESET}"
+echo -e "${COLOR_INFO}Enabling Flathub...${COLOR_RESET}"
 flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo || { echo "${COLOR_ERROR}Failed to enable Flathub${COLOR_RESET}"; exit 1; }
 
 # Enable ly
@@ -49,9 +47,7 @@ chmod u+rwx .config/hypr/xdg-portal-hyprland || { echo "${COLOR_ERROR}Failed to 
 
 # Removing desktop entries that I don't use
 echo -e "${COLOR_INFO}Removing desktop entries...${COLOR_RESET}"
-cd /usr/share/applications
-sudo rm avahi-discover.desktop bssh.desktop bvnc.desktop lstopo.desktop qv4l2.desktop qvidcap.desktop
-cd ~
+(cd /usr/share/applications && sudo rm avahi-discover.desktop bssh.desktop bvnc.desktop lstopo.desktop qv4l2.desktop qvidcap.desktop)
 
 # Final message
 echo -e "${COLOR_INFO}You can now restart your computer or manually start Hyprland via \"Hyprland\"${COLOR_RESET}"
