Much better and complete install process

diff --git a/install b/install
--- a/install
+++ b/install
@@ -14,20 +14,25 @@ if [ "$(id -u)" -eq "0" ]; then
     exit
 fi
 
-# Install yay
-echo -e "${COLOR_INFO}Installing yay...${COLOR_RESET}"
-git clone https://aur.archlinux.org/yay-git.git ~/yay-git || { echo "${COLOR_ERROR}Failed to clone yay${COLOR_RESET}"; exit 1; }
-(cd ~/yay-git && makepkg -si) || { echo "${COLOR_ERROR}Failed to install yay${COLOR_RESET}"; exit 1; }
+# Check if yay is not installed
+if ! command -v yay &> /dev/null
+then
+  # Install yay
+  echo -e "${COLOR_INFO}Installing yay...${COLOR_RESET}"
+  sudo pacman --needed --noconfirm -S git base-devel
+  git clone https://aur.archlinux.org/yay-git.git ~/yay-git || { echo "${COLOR_ERROR}Failed to clone yay${COLOR_RESET}"; exit 1; }
+  (cd ~/yay-git && makepkg -si) || { echo "${COLOR_ERROR}Failed to install yay${COLOR_RESET}"; exit 1; }
+fi
 
 # Install required packages
 echo -e "${COLOR_INFO}Installing required packages...${COLOR_RESET}"
-yay -S - < ./packages || { echo "${COLOR_ERROR}Failed to install required packages${COLOR_RESET}"; exit 1; }
+yay --needed --noconfirm -S - < ./packages || { echo "${COLOR_ERROR}Failed to install required packages${COLOR_RESET}"; exit 1; }
 
 # Enable Flathub
 echo -e "${COLOR_INFO}Enabling Flathub...${COLOR_RESET}"
 flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo || { echo "${COLOR_ERROR}Failed to enable Flathub${COLOR_RESET}"; }
 
-# Enable ly
+# Enable sddm
 echo -e "${COLOR_INFO}Enabling sddm...${COLOR_RESET}"
 sudo systemctl enable sddm || { echo "${COLOR_ERROR}Failed to enable sddm${COLOR_RESET}"; }
 
@@ -38,30 +43,27 @@ sudo systemctl enable bluetooth || { echo "${COLOR_ERROR}Failed to enable blueto
 # Copy config files and bashrc
 echo -e "${COLOR_INFO}Copying config files and bashrc...${COLOR_RESET}"
 cp -f -r .config/* ~/.config/ || { echo "${COLOR_ERROR}Failed to copy config files${COLOR_RESET}"; }
+cp -f -r .local/* ~/.local/ || { echo "${COLOR_ERROR}Failed to copy local files${COLOR_RESET}"; }
 cp -f .bashrc ~/.bashrc || { echo "${COLOR_ERROR}Failed to copy bashrc${COLOR_RESET}"; }
 
 # Making scripts executable
 echo -e "${COLOR_INFO}Making scripts executable...${COLOR_RESET}"
+chmod u+rwx .local/bin/* || { echo "${COLOR_ERROR}Failed to change permissions for .local/bin/*${COLOR_RESET}"; }
 chmod u+rwx .config/waybar/scripts/* || { echo "${COLOR_ERROR}Failed to change permissions for .config/waybar/scripts/*${COLOR_RESET}"; }
-chmod u+rwx .config/hypr/xdg-portal-hyprland || { echo "${COLOR_ERROR}Failed to change permissions for .config/hypr/xdg-portal-hyprland${COLOR_RESET}"; }
-
-# Enabling Hyprland plugins using hyprpm
-echo -e "${COLOR_INFO}Enabling plugins using Hyprpm...${COLOR_RESET}"
-hyprpm add https://github.com/Duckonaut/split-monitor-workspaces || { echo "${COLOR_ERROR}Failed to add 'split-monitor-workspaces' plugin${COLOR_RESET}"; }
-hyprpm enable split-monitor-workspaces || { echo "${COLOR_ERROR}Failed to enable 'split-monitor-workspaces' plugin${COLOR_RESET}"; }
-
-# Removing desktop entries that I don't use
-echo -e "${COLOR_INFO}Removing desktop entries...${COLOR_RESET}"
-(cd /usr/share/applications && sudo rm avahi-discover.desktop bssh.desktop bvnc.desktop lstopo.desktop qv4l2.desktop qvidcap.desktop thunar-bulk-rename.desktop thunar-settings.desktop thunar-volman-settings.desktop) || { echo "${COLOR_ERROR}Failed to remove desktop unnecesary desktop entries${COLOR_RESET}"}
 
 # Creating default directories
 echo -e "${COLOR_INFO}Creating default user directories...${COLOR_RESET}"
-xdg-user-dirs-update --force || { echo "${COLOR_ERROR}Failed to create default user directories${COLOR_RESET}"}
+xdg-user-dirs-update --force || { echo "${COLOR_ERROR}Failed to create default user directories${COLOR_RESET}"; }
 
-# Applying default Catppuccin-Mocha-Standard-Blue-Dark Theme
-echo -e "${COLOR_INFO}Applying default theme (Catppuccin-Mocha-Standard-Blue-Dark) you can change the theme later graphically with nwg-look...${COLOR_RESET}"
-gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Mocha-Standard-Blue-Dark" || { echo "${COLOR_ERROR}Failed to apply default theme${COLOR_RESET}"}
+# Applying default auto color theme
+echo -e "${COLOR_INFO}Applying GTK theme for auto color change...${COLOR_RESET}"
+gsettings set org.gnome.desktop.interface gtk-theme "AutoColor" || { echo "${COLOR_ERROR}Failed to apply default theme${COLOR_RESET}"; }
+
+# Removing window buttons (minimize, maximize, close)
+echo -e "${COLOR_INFO}Removing window buttons (minimize, maximize, close)...${COLOR_RESET}"
+gsettings set org.gnome.desktop.wm.preferences button-layout : || { echo "${COLOR_ERROR}Failed to remove window buttons${COLOR_RESET}"; }
 
 # Final message
 echo -e "${COLOR_INFO}You can now restart your computer or manually start Hyprland via \"Hyprland\"${COLOR_RESET}"
 echo -e "${COLOR_INFO}Enjoy your new system $USER!${COLOR_RESET}"
+cd ~
